# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-09 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0009_auto_20190808_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='mall_id',
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='mall_uid',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='商城uid'),
        ),
    ]
