import time

ARTICLE_STATUS_PASS = 11
ARTICLE_STATUS_WAIT = 12
ARTICLE_STATUS_FAIL = 13
ARTICLE_STATUS_CHOICES = ((ARTICLE_STATUS_PASS,'审核已通过'),
                          (ARTICLE_STATUS_WAIT,'等待审核中'),
                          (ARTICLE_STATUS_PASS,'审核未通过'))

AUTHOR_GENDER_MAN = 11
AUTHOR_GENDER_WOMAN = 12
AUTHOR_GENDER_CHOICES = ((AUTHOR_GENDER_MAN,'男'),
                         (AUTHOR_GENDER_WOMAN,'女'))

USER_GENDER_MAN = 1
USER_GENDER_WOMAN = 2
USER_GENDER_SHADOW = 3
USER_GENDER_CHOICES = (
        (USER_GENDER_MAN,'男'),
        (USER_GENDER_WOMAN,'女'),
        (USER_GENDER_SHADOW,'保密')
    )


ORDER_STATUS_INIT = 10
ORDER_STATUS_SUBMIT = 11
ORDER_STATUS_PAIED = 12
ORDER_STATUS_SEND = 13
ORDER_STATUS_DONE = 14
ORDER_STATUS_DELETED = 15
ORDER_STATUS_CHOICES = (
    (ORDER_STATUS_INIT,"购物车"),
    (ORDER_STATUS_SUBMIT,"已提交"),
    (ORDER_STATUS_PAIED,"已支付"),
    (ORDER_STATUS_SEND,"已发送"),
    (ORDER_STATUS_DONE,"已收货"),
    (ORDER_STATUS_DELETED,"已删除")
)


GOODS_STATUS_SELL = 1
GOODS_STATUS_EMPTY = 2
GOODS_STATUS_OFF = 3
GOODS_STATUS_WAIT = 4
GOODS_STATUS_DISCOUNT = 5

GOODS_STATUS=((1,'销售中'),
              (2,'已售完'),
              (3,'已下架'),
              (4,'未上架'),
              (5,'折扣中'))

USER_PAIED = 1
USER_UNPAY = 0
USER_BALANCE_STATUS = ((USER_PAIED,'已支付'),(USER_UNPAY,'未支付'))



