# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-07 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0007_auto_20190807_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommentmodel',
            name='to_recode',
            field=models.UUIDField(blank=True, null=True, verbose_name='子评论中对方用户uid'),
        ),
    ]
