# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-09 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_usermessageaccept'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='联系邮箱'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='post_code',
            field=models.CharField(default=4300654333, max_length=10, verbose_name='邮政编码'),
            preserve_default=False,
        ),
    ]
