# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-01 01:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, verbose_name='商品uid')),
                ('goods_name', models.CharField(max_length=32, verbose_name='商品名称')),
                ('goods_price', models.FloatField(verbose_name='商品价格')),
                ('goods_image', models.ImageField(upload_to='goods', verbose_name='商品图片')),
                ('goods_count', models.IntegerField(default=0, verbose_name='商品库存')),
                ('goods_number', models.IntegerField(verbose_name='商品剩余库存')),
                ('goods_description', models.TextField(verbose_name='商品描述')),
                ('goods_date', models.DateField(verbose_name='出厂日期')),
                ('goods_safedate', models.IntegerField(verbose_name='保质期')),
                ('goods_status', models.IntegerField(choices=[(1, '销售中'), (2, '已售完'), (3, '已下架'), (4, '未上架'), (5, '折扣中')], default=1, verbose_name='商品状态')),
                ('buy_link', models.CharField(blank=True, max_length=256, null=True, verbose_name='购买链接')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('reorder', models.SmallIntegerField(default=0, verbose_name='排序')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name_plural': '商品列表',
                'ordering': ['-reorder'],
            },
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='类型名称')),
                ('code', models.CharField(blank=True, max_length=32, null=True, verbose_name='编码')),
                ('description', models.CharField(blank=True, max_length=128, null=True, verbose_name='类型描述')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='goods_type', verbose_name='类型图片')),
                ('reorder', models.SmallIntegerField(default=0, verbose_name='排序')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name_plural': '商品标签',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.GoodsType', verbose_name='商品类型'),
        ),
    ]
