# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-09 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='goods_img', verbose_name='商品图片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '商品图片',
            },
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_image',
            field=models.ImageField(upload_to='goods', verbose_name='商品封面图片'),
        ),
        migrations.AddField(
            model_name='goodsimage',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_img', to='mall.Goods'),
        ),
    ]
