# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-09 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_articleimagemodel'),
        ('mall', '0002_auto_20190809_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='tag',
            field=models.ManyToManyField(blank=True, to='article.Tag'),
        ),
    ]
