# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-06 23:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='评论用户ID')),
                ('u_name', models.CharField(max_length=64, verbose_name='评论昵称')),
                ('u_code', models.UUIDField(default=uuid.uuid4, verbose_name='用户uid')),
                ('u_mail', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('mycity', models.CharField(default='未知', max_length=125, verbose_name='用户地址')),
                ('u_url', models.CharField(blank=True, max_length=225, null=True, verbose_name='用户导航')),
                ('txtContent', models.TextField(max_length=500, verbose_name='评论')),
                ('img', models.CharField(default='6', max_length=32, verbose_name='用户头像')),
                ('art_uid', models.CharField(blank=True, max_length=225, null=True, verbose_name='文章uid')),
                ('note_id', models.IntegerField(verbose_name='随笔id')),
                ('level_msg_id', models.IntegerField(verbose_name='随笔id')),
                ('photo_id', models.IntegerField(verbose_name='随笔id')),
                ('mall_id', models.IntegerField(verbose_name='随笔id')),
                ('qq', models.CharField(blank=True, max_length=16, null=True, verbose_name='评论QQ')),
                ('tel', models.CharField(blank=True, max_length=16, null=True, verbose_name='评论电话')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
            ],
        ),
        migrations.CreateModel(
            name='ReCommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=64, verbose_name='评论昵称')),
                ('u_code', models.UUIDField(default=uuid.uuid4, verbose_name='用户uid')),
                ('to_code', models.CharField(blank=True, max_length=225, null=True, verbose_name='文章uid')),
                ('txtContent', models.TextField(max_length=500, verbose_name='评论')),
                ('img', models.CharField(default='6', max_length=32, verbose_name='用户头像')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomment', to='comment.CommentModel', verbose_name='子评论')),
            ],
        ),
    ]
