# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-07 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0006_recommentmodel_self_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommentmodel',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recomment', to='comment.CommentModel', verbose_name='子评论'),
        ),
    ]
