# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-07 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20190807_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='user_id',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='评论用户ID'),
        ),
    ]
