# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-08 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0008_recommentmodel_to_recode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='level_msg_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='留言id'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='mall_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='积分商城id'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='photo_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='相册id'),
        ),
    ]
