# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-02 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190801_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='integral',
        ),
        migrations.AddField(
            model_name='userintegral',
            name='integral',
            field=models.IntegerField(default=0, verbose_name='用户的积分'),
        ),
        migrations.AddField(
            model_name='userintegral',
            name='is_fresh',
            field=models.BooleanField(default=1, verbose_name='是否刷新'),
        ),
    ]
