# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-05 10:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190803_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='短信息标题')),
                ('content', models.TextField(verbose_name='短信息内容')),
                ('to_user', models.IntegerField(verbose_name='接收用户id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_message', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '站内信息',
            },
        ),
        migrations.AlterModelOptions(
            name='userintegral',
            options={'ordering': ['-created_at']},
        ),
    ]
