# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-10 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20190809_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='goods_store',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='商品id'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='post_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='邮政编码'),
        ),
    ]
