# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-01 01:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['is_top', '-is_best', '-reorder', '-created_at'], 'verbose_name_plural': '文章列表'},
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name_plural': '作者列表'},
        ),
        migrations.AlterModelOptions(
            name='classify',
            options={'verbose_name_plural': '分类列表'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': '标签列表'},
        ),
    ]
