# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-14 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_auto_20190809_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='描述')),
                ('types', models.SmallIntegerField(choices=[(11, '置顶')], default=11, verbose_name='展示位置')),
                ('img', models.ImageField(upload_to='slider', verbose_name='图片')),
                ('reorder', models.SmallIntegerField(default=0, help_text='数字越大越靠前', verbose_name='排序')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='生效时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('target_url', models.CharField(blank=True, max_length=256, null=True, verbose_name='跳转地址')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否生效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '轮播图列表',
                'db_table': 'system_slider',
                'ordering': ['-reorder'],
            },
        ),
    ]
