from django.conf.urls import url

from accounts import views

urlpatterns = [
    url(r'user/login/$',views.user_login,name="user_login"),
    url(r'user/logout/$',views.user_logout,name="user_logout"),
    url(r'user/register/$',views.user_register,name="user_register"),
    url(r'verify/code/$',views.verify_code,name="verify_code"),
    url(r'user/center/index/$',views.user_center_index,name="user_center_index"),
    url(r'user/center/proinfo/$',views.user_center_proinfo,name="user_center_proinfo"),
    url(r'user/center/password/$',views.user_center_password,name="user_center_password"),
    url(r'user/center/convert/$',views.user_point_convert,name="user_point_convert"),
    url(r'user/center/list/$',views.UserIntegralList.as_view(),name="user_point_list"),
    url(r'user/integral/del/$',views.user_integral_del,name="user_integral_del"),
    url(r'user/center/recharge/$',views.UserRecharge.as_view(),name="user_center_recharge"),
    url(r'user/amount/log/$',views.UserBalanceView.as_view(),name="user_amount_log"),
    url(r'user/balance/del',views.UserBalanceDel.as_view(),name="user_balance_del"),
    url(r'user/balance/list',views.user_balance_list,name="user_balance_list"),
    url(r'user/collect/$',views.UserCollectView.as_view(),name="user_collect"),
    url(r'user/collect/del/$',views.UserCollectDel.as_view(),name="user_collect_del"),
    url(r'user/center/avatar/$',views.user_center_avatar,name="user_center_avatar"),
    url(r'user/message/add/$',views.UserMessageAdd.as_view(),name="user_message_add"),
    url(r'user/message/accept/list/$',views.UserMessageList.as_view(),name="user_message_accept_list"),
    url(r'user/message/send/list/$',views.UserMessageList.as_view(template_name='user_manage/user_message_send.html'),name="user_message_send_list"),
    url(r'user/message/system/list/$',views.UserMessageList.as_view(template_name='user_manage/user_message_system.html'),name="user_message_system_list"),
    url(r'user/message/del/$',views.UserMessageDel.as_view(),name="user_message_del"),
    url(r'user/message/accept/del/$', views.UserMessageAcceptDel.as_view(), name="user_message_accept_del"),
    url(r'user/message/detail/(?P<pk>\S+)$', views.UserMessageDetail.as_view(), name="user_message_detail"),
    url(r'user/message/accept/detail/(?P<pk>\S+)$', views.UserMessageAcceptDetail.as_view(), name="user_message_accept_detail"),
    url(r'user/address/add/$',views.UserAddressView.as_view(),name="user_address_add"),
    url(r'user/address/list/$', views.UserAddressList.as_view(), name="user_address_list"),
    url(r'user/address/del/$',views.UserAddressDel.as_view(),name="user_address_del"),
    url(r'user/address/set/default/$',views.UserAddressSetDefault.as_view(),name="user_address_set_default"),
    url(r'user/shopping/list/$',views.UserShoppingList.as_view(),name="user_shopping_list"),
    url(r'user/shopping/del/$',views.UserShoppingDel.as_view(),name="user_shopping_del"),
    url(r'user/order/create/$',views.UserOrderCreate.as_view(),name="user_order_create"),
    url(r'user/order/list/$',views.UserOrderList.as_view(),name="user_order_list"),
    url(r'user/order/del/$', views.UserOrderDel.as_view(), name="user_order_del"),
    url(r'user/order/detail/$',views.UserOrderDetail.as_view(),name="user_order_detail"),
    url(r'user/order/pay/$',views.PayOrder.as_view(),name="user_order_pay"),
    url(r'user/article/edit/$',views.UserArticleEdit.as_view(),name="user_article_edit"),
    url(r'user/article/list/$',views.UserArticleList.as_view(),name="user_article_list"),
    url(r'user/article/del/$', views.UserArticleDel.as_view(), name="user_article_del"),
]