# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-06 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userwrite',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='userwrite',
            name='address',
            field=models.CharField(default='北京市朝阳区', max_length=64, verbose_name='目前所在'),
        ),
        migrations.AddField(
            model_name='userwrite',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='浏览次数'),
        ),
    ]
