# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-19 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_auto_20190819_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='img',
            field=models.ImageField(blank=True, default='video/1.jpg', null=True, upload_to='video', verbose_name='视频封面图片'),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='reorder',
            field=models.IntegerField(default=0, verbose_name='视频排序'),
        ),
    ]
