# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-07 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='level_msg_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='随笔id'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='mall_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='随笔id'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='note_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='随笔id'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='photo_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='随笔id'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='user_id',
            field=models.IntegerField(default=0, verbose_name='评论用户ID'),
        ),
        migrations.AlterField(
            model_name='recommentmodel',
            name='img',
            field=models.CharField(default='7', max_length=32, verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='recommentmodel',
            name='to_code',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='对方用户uid'),
        ),
    ]
