# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-01 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190801_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='img',
            field=models.ImageField(upload_to='cart', verbose_name='商品主图'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='goods_image',
            field=models.ImageField(upload_to='%Y%m_order', verbose_name='商品图片'),
        ),
    ]
