# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-01 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190801_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='growth_value',
            field=models.IntegerField(default=0, verbose_name='成长值'),
        ),
    ]
