# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-05 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20190805_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '已读'), (0, '未读')], default=0, verbose_name='是否已读'),
        ),
    ]
