# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-29 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, verbose_name='文章uid')),
                ('title', models.CharField(max_length=64, verbose_name='文章标题')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('summary', models.CharField(blank=True, max_length=200, null=True, verbose_name='文章简介')),
                ('img', models.ImageField(blank=True, default='/media/201907/1.jpg', null=True, upload_to='%Y%m', verbose_name='文章标题图片')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='浏览次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('source', models.CharField(blank=True, max_length=64, null=True, verbose_name='文章来源')),
                ('status', models.SmallIntegerField(choices=[(11, '审核已通过'), (12, '等待审核中'), (11, '审核未通过')], default=11, verbose_name='文章审核')),
                ('is_valid', models.BooleanField(default=1, verbose_name='是否有效')),
                ('reorder', models.IntegerField(default=0, verbose_name='文章排序')),
                ('is_top', models.BooleanField(default=0, verbose_name='是否置顶')),
                ('is_best', models.BooleanField(default=0, verbose_name='是否推荐')),
            ],
            options={
                'ordering': ['is_top', '-is_best', '-reorder', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='作者姓名')),
                ('gender', models.SmallIntegerField(choices=[(11, '男'), (12, '女')], default=11, verbose_name='作者性别')),
                ('age', models.SmallIntegerField(default=0, verbose_name='作者年龄')),
            ],
        ),
        migrations.CreateModel(
            name='Classify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='类型名称')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='标签名称')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='article.Author'),
        ),
        migrations.AddField(
            model_name='article',
            name='classify',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classify', to='article.Classify'),
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(blank=True, to='article.Tag'),
        ),
    ]
