# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-12 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0010_auto_20190809_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='level_msg_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='随笔id'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='note_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='留言id'),
        ),
    ]
