# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-16 23:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20190812_0953'),
        ('comment', '0011_auto_20190812_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='art_uid',
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='article.Article', verbose_name='文章'),
        ),
    ]
