# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-01 01:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20190801_0137'),
        ('mall', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='商品名称')),
                ('img', models.ImageField(upload_to='static/buyer/cart', verbose_name='商品主图')),
                ('price', models.IntegerField(verbose_name='商品单价')),
                ('count', models.PositiveIntegerField(verbose_name='购买的数量')),
                ('total_price', models.FloatField(verbose_name='商品总价')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='mall.Goods')),
            ],
        ),
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classify', models.CharField(max_length=32, verbose_name='文章类别')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collect', to='article.Article')),
            ],
            options={
                'verbose_name_plural': '用户收藏',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.CharField(max_length=32, verbose_name='id订单编号')),
                ('goods_count', models.IntegerField(verbose_name='商品数量')),
                ('order_price', models.FloatField(verbose_name='订单总价')),
                ('order_status', models.SmallIntegerField(choices=[(10, '购物车'), (11, '已提交'), (12, '已支付'), (13, '已发送'), (14, '已收货'), (15, '已删除')], default=11, verbose_name='订单状态')),
                ('remark', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
                ('express_type', models.CharField(blank=True, max_length=32, null=True, verbose_name='快递信息')),
                ('express_no', models.CharField(blank=True, max_length=64, null=True, verbose_name='快递单号')),
                ('status', models.SmallIntegerField(choices=[(10, '购物车'), (11, '已提交'), (12, '已支付'), (13, '已发送'), (14, '已收货'), (15, '已删除')], default=11, verbose_name='订单状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='accounts.UserAddress', verbose_name='订单地址')),
            ],
            options={
                'verbose_name_plural': '订单管理',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.IntegerField(verbose_name='商品id')),
                ('goods_name', models.CharField(max_length=32, verbose_name='商品名称')),
                ('goods_price', models.FloatField(verbose_name='商品价格')),
                ('goods_number', models.IntegerField(verbose_name='商品购买数量')),
                ('goods_total', models.FloatField(verbose_name='商品总价')),
                ('goods_store', models.IntegerField(verbose_name='商品id')),
                ('goods_image', models.ImageField(upload_to='static/buyer/%Y%m_order', verbose_name='商品图片')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_detail', to='accounts.Order', verbose_name='订单编号')),
            ],
        ),
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=128, verbose_name='充值单号')),
                ('method', models.CharField(max_length=32, verbose_name='支付方式')),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='充值金额')),
                ('status', models.SmallIntegerField(choices=[(1, '已支付'), (0, '未支付')], default=0, verbose_name='支付状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='UserIntegral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='每日登陆获得积分', max_length=200, verbose_name='积分来源')),
                ('detail', models.CharField(default='+5', max_length=16, verbose_name='积分明细')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='level',
        ),
        migrations.AddField(
            model_name='loginrecord',
            name='integral',
            field=models.IntegerField(default=0, verbose_name='用户积分'),
        ),
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='余额'),
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.IntegerField(default=0, verbose_name='用户等级'),
        ),
        migrations.AddField(
            model_name='user',
            name='sign',
            field=models.CharField(default='困而知之,学而知之,生而知之', max_length=32, verbose_name='个性签名'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='详细地址'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='area',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='区域'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='城市'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='province',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='省份'),
        ),
        migrations.AlterField(
            model_name='passwdchangelog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pw_change', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='integral',
            field=models.IntegerField(default=0, verbose_name='用户的积分'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='real_name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='真实姓名'),
        ),
        migrations.AddField(
            model_name='userintegral',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_integral', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userbalance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_balance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL, verbose_name='订单用户'),
        ),
        migrations.AddField(
            model_name='collect',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_collect', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL),
        ),
    ]
