# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-08 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20190806_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_name', models.CharField(max_length=120, verbose_name='网站名称')),
                ('contact_man', models.CharField(max_length=64, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='联系电话')),
                ('email', models.EmailField(blank=True, max_length=120, null=True, verbose_name='邮箱')),
                ('web_link', models.URLField(verbose_name='网站网址')),
                ('web_description', models.TextField(max_length=500, verbose_name='网站描述')),
                ('status', models.SmallIntegerField(choices=[(1, '审核通过'), (0, '审核未通过'), (2, '待审核')], default=2, verbose_name='申请状态')),
                ('is_inner', models.BooleanField(default=False, verbose_name='是否为内连接')),
            ],
        ),
    ]
