# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-08 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_linkmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linkmodel',
            options={'ordering': ['-created_at', '-updated_at'], 'verbose_name_plural': '友情链接'},
        ),
        migrations.AddField(
            model_name='linkmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linkmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
