# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-06 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserWrite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='KevIn', max_length=32, verbose_name='管理员')),
                ('content', models.TextField(verbose_name='随笔内容')),
                ('img', models.ImageField(blank=True, null=True, upload_to='write_some', verbose_name='随笔图片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
    ]
