# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-19 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20190812_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.SmallIntegerField(choices=[(11, '审核已通过'), (12, '等待审核中'), (13, '审核未通过'), (14, '草稿')], default=12, verbose_name='文章审核'),
        ),
    ]
