# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-26 00:05
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20190819_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='文章内容'),
        ),
    ]
