# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-26 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20190826_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('4c1cdbd8-3e31-4c6b-b1b9-0da27f267244'), verbose_name='uid编码'),
        ),
    ]
