# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-07 00:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20190807_0013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentmodel',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='recommentmodel',
            options={'ordering': ['-created_at']},
        ),
    ]
