# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-07 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_auto_20190807_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommentmodel',
            name='self_reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comment.ReCommentModel'),
        ),
    ]
