# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-19 17:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20190819_1728'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system', '0007_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, verbose_name='视频uid')),
                ('title', models.CharField(max_length=24, verbose_name='视频标题')),
                ('video', models.CharField(max_length=255, verbose_name='视频地址')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('desc', models.TextField(max_length=600, verbose_name='视频描述')),
                ('is_best', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('is_valid', models.BooleanField(default=1, verbose_name='是否有效')),
                ('reorder', models.IntegerField(default=0, verbose_name='文章排序')),
                ('is_top', models.BooleanField(default=0, verbose_name='是否置顶')),
                ('source', models.CharField(blank=True, max_length=64, null=True, verbose_name='视频来源')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '我的视频',
            },
        ),
        migrations.CreateModel(
            name='VideoType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, verbose_name='视频类型名称')),
                ('code', models.CharField(max_length=6, verbose_name='视频类型编码')),
            ],
            options={
                'verbose_name_plural': '视频类型',
            },
        ),
        migrations.AddField(
            model_name='videomodel',
            name='classify',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.VideoType'),
        ),
        migrations.AddField(
            model_name='videomodel',
            name='tag',
            field=models.ManyToManyField(blank=True, to='article.Tag'),
        ),
        migrations.AddField(
            model_name='videomodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to=settings.AUTH_USER_MODEL),
        ),
    ]
